// teamLogos.js
const teamLogos = {
  "en.1": {
    leagueName: "Premier League",
    logos: {
      "AFC Bournemouth": "/assets/img/premierleague/AFC Bournemouth.png",
      "Arsenal FC": "/assets/img/premierleague/Arsenal FC.png",
      "Aston Villa FC": "/assets/img/premierleague/Aston Villa.png",
      "Brentford FC": "/assets/img/premierleague/Brentford FC.png",
      "Brighton & Hove Albion FC":
        "/assets/img/premierleague/Brighton & Hove Albion.png",
      "Chelsea FC": "/assets/img/premierleague/Chelsea FC.png",
      "Crystal Palace FC": "/assets/img/premierleague/Crystal Palace.png",
      "Everton FC": "/assets/img/premierleague/Everton FC.png",
      "Fulham FC": "/assets/img/premierleague/Fulham FC.png",
      "Ipswich Town FC": "/assets/img/premierleague/Ipswich Town.png",
      "Leicester City FC": "/assets/img/premierleague/Leicester City.png",
      "Liverpool FC": "/assets/img/premierleague/Liverpool FC.png",
      "Manchester City FC": "/assets/img/premierleague/Manchester City.png",
      "Manchester United FC": "/assets/img/premierleague/Manchester United.png",
      "Newcastle United FC": "/assets/img/premierleague/Newcastle United.png",
      "Nottingham Forest FC": "/assets/img/premierleague/Nottingham Forest.png",
      "Southampton FC": "/assets/img/premierleague/Southampton FC.png",
      "Tottenham Hotspur FC": "/assets/img/premierleague/Tottenham Hotspur.png",
      "West Ham United FC": "/assets/img/premierleague/West Ham United.png",
      "Wolverhampton Wanderers FC":
        "/assets/img/premierleague/Wolverhampton Wanderers.png",
    },
  },
  "es.1": {
    leagueName: "La Liga",
    logos: {
      "Athletic Club": "/assets/img/laliga/Athletic Bilbao.png",
      "Club Atlético de Madrid": "/assets/img/laliga/Atlético de Madrid.png",
      "CA Osasuna": "/assets/img/laliga/CA Osasuna.png",
      "CD Leganés": "/assets/img/laliga/CD Leganés.png",
      "RC Celta de Vigo": "/assets/img/laliga/Celta de Vigo.png",
      "Deportivo Alavés": "/assets/img/laliga/Deportivo Alavés.png",
      "FC Barcelona": "/assets/img/laliga/FC Barcelona.png",
      "Getafe CF": "/assets/img/laliga/Getafe CF.png",
      "Girona FC": "/assets/img/laliga/Girona FC.png",
      "Rayo Vallecano de Madrid": "/assets/img/laliga/Rayo Vallecano.png",
      "RCD Espanyol de Barcelona":
        "/assets/img/laliga/RCD Espanyol Barcelona.png",
      "RCD Mallorca": "/assets/img/laliga/RCD Mallorca.png",
      "Real Betis Balompié": "/assets/img/laliga/Real Betis Balompié.png",
      "Real Madrid CF": "/assets/img/laliga/Real Madrid.png",
      "Real Sociedad de Fútbol": "/assets/img/laliga/Real Sociedad.png",
      "Real Valladolid CF": "/assets/img/laliga/Real Valladolid CF.png",
      "Sevilla FC": "/assets/img/laliga/Sevilla FC.png",
      "UD Las Palmas": "/assets/img/laliga/UD Las Palmas.png",
      "Valencia CF": "/assets/img/laliga/Valencia CF.png",
      "Villarreal CF": "/assets/img/laliga/Villarreal CF.png",
    },
  },
  "de.1": {
    leagueName: "Bundesliga",
    logos: {
      "1. FC Heidenheim 1846":
        "/assets/img/bundesliga/1.FC Heidenheim 1846.png",
      "1. FC Union Berlin": "/assets/img/bundesliga/1.FC Union Berlin.png",
      "1. FSV Mainz 05": "/assets/img/bundesliga/1.FSV Mainz 05.png",
      "Bayer 04 Leverkusen": "/assets/img/bundesliga/Bayer 04 Leverkusen.png",
      "FC Bayern München": "/assets/img/bundesliga/Bayern Munich.png",
      "Borussia Dortmund": "/assets/img/bundesliga/Borussia Dortmund.png",
      "Borussia Mönchengladbach":
        "/assets/img/bundesliga/Borussia Mönchengladbach.png",
      "Eintracht Frankfurt": "/assets/img/bundesliga/Eintracht Frankfurt.png",
      "FC Augsburg": "/assets/img/bundesliga/FC Augsburg.png",
      "FC St. Pauli 1910": "/assets/img/bundesliga/FC St. Pauli.png",
      "Holstein Kiel": "/assets/img/bundesliga/Holstein Kiel.png",
      "RB Leipzig": "/assets/img/bundesliga/RB Leipzig.png",
      "SC Freiburg": "/assets/img/bundesliga/SC Freiburg.png",
      "SV Werder Bremen": "/assets/img/bundesliga/SV Werder Bremen.png",
      "TSG 1899 Hoffenheim": "/assets/img/bundesliga/TSG 1899 Hoffenheim.png",
      "VfB Stuttgart": "/assets/img/bundesliga/VfB Stuttgart.png",
      "VfL Bochum 1848": "/assets/img/bundesliga/VfL Bochum.png",
      "VfL Wolfsburg": "/assets/img/bundesliga/VfL Wolfsburg.png",
    },
  },
  "it.1": {
    leagueName: "Serie A",
    logos: {
      "AC Milan": "/assets/img/seriea/AC Milan.png",
      "AC Monza": "/assets/img/seriea/AC Monza.png",
      "ACF Fiorentina": "/assets/img/seriea/ACF Fiorentina.png",
      "AS Roma": "/assets/img/seriea/AS Roma.png",
      "Atalanta BC": "/assets/img/seriea/Atalanta BC.png",
      "Bologna FC 1909": "/assets/img/seriea/Bologna FC 1909.png",
      "Cagliari Calcio": "/assets/img/seriea/Cagliari Calcio.png",
      "Como 1907": "/assets/img/seriea/Como 1907.png",
      "Empoli FC": "/assets/img/seriea/FC Empoli.png",
      "Genoa CFC": "/assets/img/seriea/Genoa CFC.png",
      "FC Internazionale Milano": "/assets/img/seriea/Inter Milan.png",
      "Juventus FC": "/assets/img/seriea/Juventus FC.png",
      "Parma Calcio 1913": "/assets/img/seriea/Parma Calcio 1913.png",
      "SS Lazio": "/assets/img/seriea/SS Lazio.png",
      "SSC Napoli": "/assets/img/seriea/SSC Napoli.png",
      "Torino FC": "/assets/img/seriea/Torino FC.png",
      "Udinese Calcio": "/assets/img/seriea/Udinese Calcio.png",
      "US Lecce": "/assets/img/seriea/US Lecce.png",
      "Venezia FC": "/assets/img/seriea/Venezia FC.png",
      "Hellas Verona FC": "/assets/img/seriea/Hellas Verona.png",
    },
  },
};

export default teamLogos;
