const teamLogos = {
  "en.1": {
    leagueName: "English Premier League",
    displayName: "Premier League",
    leagueLogo: require("../../assets/img/premierleague/premierLeague.png"),
    logos: {
      "AFC Bournemouth": require("../../assets/img/premierleague/AFC Bournemouth.png"),
      "Arsenal FC": require("../../assets/img/premierleague/Arsenal FC.png"),
      "Aston Villa FC": require("../../assets/img/premierleague/Aston Villa.png"),
      "Brentford FC": require("../../assets/img/premierleague/Brentford FC.png"),
      "Brighton & Hove Albion FC": require("../../assets/img/premierleague/Brighton & Hove Albion.png"),
      "Chelsea FC": require("../../assets/img/premierleague/Chelsea FC.png"),
      "Crystal Palace FC": require("../../assets/img/premierleague/Crystal Palace.png"),
      "Everton FC": require("../../assets/img/premierleague/Everton FC.png"),
      "Fulham FC": require("../../assets/img/premierleague/Fulham FC.png"),
      "Ipswich Town FC": require("../../assets/img/premierleague/Ipswich Town.png"),
      "Leicester City FC": require("../../assets/img/premierleague/Leicester City.png"),
      "Liverpool FC": require("../../assets/img/premierleague/Liverpool FC.png"),
      "Manchester City FC": require("../../assets/img/premierleague/Manchester City.png"),
      "Manchester United FC": require("../../assets/img/premierleague/Manchester United.png"),
      "Newcastle United FC": require("../../assets/img/premierleague/Newcastle United.png"),
      "Nottingham Forest FC": require("../../assets/img/premierleague/Nottingham Forest.png"),
      "Southampton FC": require("../../assets/img/premierleague/Southampton FC.png"),
      "Tottenham Hotspur FC": require("../../assets/img/premierleague/Tottenham Hotspur.png"),
      "West Ham United FC": require("../../assets/img/premierleague/West Ham United.png"),
      "Wolverhampton Wanderers FC": require("../../assets/img/premierleague/Wolverhampton Wanderers.png"),
    },
  },
  "es.1": {
    leagueName: "Spain Primera Division",
    displayName: "La Liga",
    leagueLogo: require("../../assets/img/laliga/LaLiga.png"),
    logos: {
      "Athletic Club": require("../../assets/img/laliga/Athletic Bilbao.png"),
      "Club Atlético de Madrid": require("../../assets/img/laliga/Atlético de Madrid.png"),
      "CA Osasuna": require("../../assets/img/laliga/CA Osasuna.png"),
      "CD Leganés": require("../../assets/img/laliga/CD Leganés.png"),
      "RC Celta de Vigo": require("../../assets/img/laliga/Celta de Vigo.png"),
      "Deportivo Alavés": require("../../assets/img/laliga/Deportivo Alavés.png"),
      "FC Barcelona": require("../../assets/img/laliga/FC Barcelona.png"),
      "Getafe CF": require("../../assets/img/laliga/Getafe CF.png"),
      "Girona FC": require("../../assets/img/laliga/Girona FC.png"),
      "Rayo Vallecano de Madrid": require("../../assets/img/laliga/Rayo Vallecano.png"),
      "RCD Espanyol de Barcelona": require("../../assets/img/laliga/RCD Espanyol Barcelona.png"),
      "RCD Mallorca": require("../../assets/img/laliga/RCD Mallorca.png"),
      "Real Betis Balompié": require("../../assets/img/laliga/Real Betis Balompié.png"),
      "Real Madrid CF": require("../../assets/img/laliga/Real Madrid.png"),
      "Real Sociedad de Fútbol": require("../../assets/img/laliga/Real Sociedad.png"),
      "Real Valladolid CF": require("../../assets/img/laliga/Real Valladolid CF.png"),
      "Sevilla FC": require("../../assets/img/laliga/Sevilla FC.png"),
      "UD Las Palmas": require("../../assets/img/laliga/UD Las Palmas.png"),
      "Valencia CF": require("../../assets/img/laliga/Valencia CF.png"),
      "Villarreal CF": require("../../assets/img/laliga/Villarreal CF.png"),
    },
  },
  "de.1": {
    leagueName: "German 1. Bundesliga",
    displayName: "Bundesliga",
    leagueLogo: require("../../assets/img/bundesliga/Bundesliga.png"),
    logos: {
      "1. FC Heidenheim 1846": require("../../assets/img/bundesliga/1.FC Heidenheim 1846.png"),
      "1. FC Union Berlin": require("../../assets/img/bundesliga/1.FC Union Berlin.png"),
      "1. FSV Mainz 05": require("../../assets/img/bundesliga/1.FSV Mainz 05.png"),
      "Bayer 04 Leverkusen": require("../../assets/img/bundesliga/Bayer 04 Leverkusen.png"),
      "FC Bayern München": require("../../assets/img/bundesliga/Bayern Munich.png"),
      "Borussia Dortmund": require("../../assets/img/bundesliga/Borussia Dortmund.png"),
      "Borussia Mönchengladbach": require("../../assets/img/bundesliga/Borussia Mönchengladbach.png"),
      "Eintracht Frankfurt": require("../../assets/img/bundesliga/Eintracht Frankfurt.png"),
      "FC Augsburg": require("../../assets/img/bundesliga/FC Augsburg.png"),
      "FC St. Pauli 1910": require("../../assets/img/bundesliga/FC St. Pauli.png"),
      "Holstein Kiel": require("../../assets/img/bundesliga/Holstein Kiel.png"),
      "RB Leipzig": require("../../assets/img/bundesliga/RB Leipzig.png"),
      "SC Freiburg": require("../../assets/img/bundesliga/SC Freiburg.png"),
      "SV Werder Bremen": require("../../assets/img/bundesliga/SV Werder Bremen.png"),
      "TSG 1899 Hoffenheim": require("../../assets/img/bundesliga/TSG 1899 Hoffenheim.png"),
      "VfB Stuttgart": require("../../assets/img/bundesliga/VfB Stuttgart.png"),
      "VfL Bochum 1848": require("../../assets/img/bundesliga/VfL Bochum.png"),
      "VfL Wolfsburg": require("../../assets/img/bundesliga/VfL Wolfsburg.png"),
    },
  },
  "it.1": {
    leagueName: "Italian Serie A",
    displayName: "Serie A",
    leagueLogo: require("../../assets/img/seriea/SerieA.png"),
    logos: {
      "AC Milan": require("../../assets/img/seriea/AC Milan.png"),
      "AC Monza": require("../../assets/img/seriea/AC Monza.png"),
      "ACF Fiorentina": require("../../assets/img/seriea/ACF Fiorentina.png"),
      "AS Roma": require("../../assets/img/seriea/AS Roma.png"),
      "Atalanta BC": require("../../assets/img/seriea/Atalanta BC.png"),
      "Bologna FC 1909": require("../../assets/img/seriea/Bologna FC 1909.png"),
      "Cagliari Calcio": require("../../assets/img/seriea/Cagliari Calcio.png"),
      "Como 1907": require("../../assets/img/seriea/Como 1907.png"),
      "Empoli FC": require("../../assets/img/seriea/FC Empoli.png"),
      "Genoa CFC": require("../../assets/img/seriea/Genoa CFC.png"),
      "FC Internazionale Milano": require("../../assets/img/seriea/Inter Milan.png"),
      "Juventus FC": require("../../assets/img/seriea/Juventus FC.png"),
      "Parma Calcio 1913": require("../../assets/img/seriea/Parma Calcio 1913.png"),
      "SS Lazio": require("../../assets/img/seriea/SS Lazio.png"),
      "SSC Napoli": require("../../assets/img/seriea/SSC Napoli.png"),
      "Torino FC": require("../../assets/img/seriea/Torino FC.png"),
      "Udinese Calcio": require("../../assets/img/seriea/Udinese Calcio.png"),
      "US Lecce": require("../../assets/img/seriea/US Lecce.png"),
      "Venezia FC": require("../../assets/img/seriea/Venezia FC.png"),
      "Hellas Verona FC": require("../../assets/img/seriea/Hellas Verona.png"),
    },
  },
};

export default teamLogos;
